# Generated by Django 3.2.8 on 2021-11-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interncorner_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='interncorner',
            name='Username',
            field=models.CharField(default='vishu', max_length=150),
            preserve_default=False,
        ),
    ]
